//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeAutomation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.2.6;Initial Catalog=CIPS;Integrated Security=true")]
        public string CIPS {
            get {
                return ((string)(this["CIPS"]));
            }
            set {
                this["CIPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.2.6;Initial Catalog=RxBackend;Integrated Security=true")]
        public string RxBackend {
            get {
                return ((string)(this["RxBackend"]));
            }
            set {
                this["RxBackend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int FAC_COLUMN {
            get {
                return ((int)(this["FAC_COLUMN"]));
            }
            set {
                this["FAC_COLUMN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("operations@ihspharmacy.com")]
        public string EmailAddress {
            get {
                return ((string)(this["EmailAddress"]));
            }
            set {
                this["EmailAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PFnCH5WMt+nIMrCEObfhVA==")]
        public string EmailPassword {
            get {
                return ((string)(this["EmailPassword"]));
            }
            set {
                this["EmailPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("outlook.office365.com")]
        public string EmailServer {
            get {
                return ((string)(this["EmailServer"]));
            }
            set {
                this["EmailServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IHS")]
        public string Mailbox {
            get {
                return ((string)(this["Mailbox"]));
            }
            set {
                this["Mailbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cips9")]
        public string DSN_CIPS {
            get {
                return ((string)(this["DSN_CIPS"]));
            }
            set {
                this["DSN_CIPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rx")]
        public string DSN_RxBackend {
            get {
                return ((string)(this["DSN_RxBackend"]));
            }
            set {
                this["DSN_RxBackend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int EmailPort {
            get {
                return ((int)(this["EmailPort"]));
            }
            set {
                this["EmailPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ActiveFax")]
        public string FaxPrinter {
            get {
                return ((string)(this["FaxPrinter"]));
            }
            set {
                this["FaxPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("q9fs2m6fm2iekpie72f5ufdvf0@group.calendar.google.com")]
        public string CalendarID {
            get {
                return ((string)(this["CalendarID"]));
            }
            set {
                this["CalendarID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\IHSADAF1\\activerx\\")]
        public string FaxFolder {
            get {
                return ((string)(this["FaxFolder"]));
            }
            set {
                this["FaxFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("keilad@ihspharmacy.com")]
        public string ForwardAddress {
            get {
                return ((string)(this["ForwardAddress"]));
            }
            set {
                this["ForwardAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Notifications\\Billing\\")]
        public string BillingRptFolder {
            get {
                return ((string)(this["BillingRptFolder"]));
            }
            set {
                this["BillingRptFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Notifications\\Exports\\")]
        public string BillingExports {
            get {
                return ((string)(this["BillingExports"]));
            }
            set {
                this["BillingExports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Files\\download\\")]
        public string download {
            get {
                return ((string)(this["download"]));
            }
            set {
                this["download"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Files\\process\\")]
        public string process {
            get {
                return ((string)(this["process"]));
            }
            set {
                this["process"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Files\\renamed\\")]
        public string renamed {
            get {
                return ((string)(this["renamed"]));
            }
            set {
                this["renamed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1630, 570")]
        public global::System.Drawing.Point fromCrop {
            get {
                return ((global::System.Drawing.Point)(this["fromCrop"]));
            }
            set {
                this["fromCrop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1920, 640")]
        public global::System.Drawing.Point toCrop {
            get {
                return ((global::System.Drawing.Point)(this["toCrop"]));
            }
            set {
                this["toCrop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int dpi {
            get {
                return ((int)(this["dpi"]));
            }
            set {
                this["dpi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Python38\\")]
        public string python {
            get {
                return ((string)(this["python"]));
            }
            set {
                this["python"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Notifications\\Exports\\")]
        public string NotifyExports {
            get {
                return ((string)(this["NotifyExports"]));
            }
            set {
                this["NotifyExports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Notifications\\Reports\\FN.rpt")]
        public string NotifyReport {
            get {
                return ((string)(this["NotifyReport"]));
            }
            set {
                this["NotifyReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zrefugee@gmail.com")]
        public string AddressAttachment {
            get {
                return ((string)(this["AddressAttachment"]));
            }
            set {
                this["AddressAttachment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OuadmfoyL8VvCpWcxbgZ9w==")]
        public string PasswordAttachment {
            get {
                return ((string)(this["PasswordAttachment"]));
            }
            set {
                this["PasswordAttachment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CIPS_WS")]
        public string DSN_WS {
            get {
                return ((string)(this["DSN_WS"]));
            }
            set {
                this["DSN_WS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZWS")]
        public string WS_ID {
            get {
                return ((string)(this["WS_ID"]));
            }
            set {
                this["WS_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Your Billing Report from IHS Pharmacy is attached")]
        public string SendEmailMessage {
            get {
                return ((string)(this["SendEmailMessage"]));
            }
            set {
                this["SendEmailMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Your Billing Report is attached")]
        public string SendEmailSubject {
            get {
                return ((string)(this["SendEmailSubject"]));
            }
            set {
                this["SendEmailSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Currently, we are testing a new billing process.  Please disregard the email that" +
            " was sent out, as it was a false start. \r\n\r\nWe currently plan on sending the Jul" +
            "y Billing on Monday, if all goes well.")]
        public string NotifyEmailMessage {
            get {
                return ((string)(this["NotifyEmailMessage"]));
            }
            set {
                this["NotifyEmailMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Issue with previous Billing Report sent")]
        public string NotifyEmailSubject {
            get {
                return ((string)(this["NotifyEmailSubject"]));
            }
            set {
                this["NotifyEmailSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\IHSSQL1\\Application Setups\\IHS Office Automation\\update\\")]
        public string update {
            get {
                return ((string)(this["update"]));
            }
            set {
                this["update"] = value;
            }
        }
    }
}
